import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footerl from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    Default :"sbagrant.gov",
    template: '%s | Grantapp',
  
  },
  description: "Generated by create next app",
  
    icons:{
      icon:"/sbaLogo.png"
    }
  
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="text-">this is AuthLayout</div>
        {children}
        
      </body>
    </html>
  );
}
