import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarWrapper from "../(home)/navbarRap"
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    Default :"sbagrant.gov",
    template: '%s | Grantapp',
  
  },
  description: "Generated by create next app",
  
    icons:{
      icon:"/sbaLogo.png"
    }
  
};

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-black overflow-x-hidden"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {/* <Navbar /> */}
         {/* < NavbarWrapper/> */}
        {children}
      </body>
    </html>
  );
}
